name: "Build and Push to Docker Hub"
description: "This is action for building and pushing docker image to Docker Hub"

inputs:
  docker-repository: 
    description: "Docker Hub repository where image should be pushed"
    required: true
  image-tag:
    description: "Tag for docker image"
    required: true
  username:
    description: "Docker Hub username"
    required: true
  password:
    description: "Docker Hub password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: Dockerfile.multistage
        tags: ${{ inputs.username }}/${{ inputs.docker-repository }}:${{ inputs.image-tag }}
