apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels: 
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: smancic/main
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_PROFILES_ACTIVE
          value: postgres
        - name: POSTGRES_URL
          value: jdbc:postgresql://postgres:5432/petclinic
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
    app: petclinic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
